---
title: Presentation at Delaware Watershed Research Conference 2018
author: Tyler Bradley
date: '2018-11-28'
slug: presentation-at-delaware-watershed-research-conference-2018
categories: []
tags:
  - ngs
  - pacbio
  - illumina
  - MST
description: ''
topics: []
---

I am pleased to announce that I will presenting at the upcoming [Delaware Watershed Reseach Conference 2018](https://ansp.org/research/environmental-research/projects/watershed-protection-program/delaware-watershed-research-conference/) at the Academy of Natural Sciences of Drexel University on Thursday November 29, 2018. My presentation is entitled "Comparing Illumina MiSeq and PacBio Sequel Sequencing of Fecal Samples from Various Animal Sources Potentially Contributing to Microbial Contamination of the Delaware River Watershed". This presentation will discuss ongoing research within the [Sales Laboratory Group](http://microbes.cae.drexel.edu/people/dr-sales) at Drexel University. 

The project is investigating the use of different next generation sequencing techniques and their ability to perform microbial source tracking. The presentation at DWRC 2018 will focus solely on the difference between the two sequencing results for just the fecal samples collected in this study. Specifically, looking at whether sequencing the full length 16S rRNA gene (done using the PacBio Sequel sequencing method) is more effective than targeting specific hyper-variable regions of the 16S rRNA gene (done using the Illumina MiSeq sequencing method). The abstract for this presentation can be found [here](https://tbradley1013.github.io/presentations/).

I will be presenting at 11 AM in the Freshwater Status and Trends track of the conference.


Please come and take a look at the research I am working on!

